In [1]:
import pandas as pd

In [2]:
pwd

'/Users/davidreynolds/projects/trustpilot_pet_insurance_reviews/notebooks'

In [122]:
embrace_reviews_all = pd.read_csv('/Users/davidreynolds/projects/trustpilot_pet_insurance_reviews/web_scraping/curated/embrace_reviews_all.csv', sep=',')

In [123]:
embrace_reviews_all.head()

,id,filtered,pending,text,rating,title,likes,experienced,published,source,provider,experienced_date,published_date,source_url
0,660d90bba202a1b7ebec9f01,False,False,I found the claims process pretty easy. The di...,5,Easy claims process!,0,2024-04-03T00:00:00.000Z,2024-04-03T19:24:11.000Z,https://www.trustpilot.com/review/embracepetin...,NaN,NaN,NaN,NaN
1,660d57925db607bf632da95b,False,False,Embrace was with me all the way when my sweet ...,5,Embrace was with me all the way,0,2024-03-12T00:00:00.000Z,2024-04-03T15:20:18.000Z,https://www.trustpilot.com/review/embracepetin...,NaN,NaN,NaN,NaN
2,660c0895a84dc6d3932a3a3b,False,False,Our beagle developed bronchitis and she needed...,5,Beagle with bronchitis.,0,2024-02-09T00:00:00.000Z,2024-04-02T15:31:02.000Z,https://www.trustpilot.com/review/embracepetin...,NaN,NaN,NaN,NaN
3,660d78c0e7539a8062cff89d,False,False,Insurance is too expensive. It goes up every y...,3,Insurance is too expensive,0,2024-01-01T00:00:00.000Z,2024-04-03T17:41:53.000Z,https://www.trustpilot.com/review/embracepetin...,NaN,NaN,NaN,NaN
4,6608beec59da2e7577de508e,False,False,Embrace Pet Insurance settled my claim quickly...,5,Embrace Pet Insurance is a wonderful company.,0,2024-03-13T00:00:00.000Z,2024-03-31T03:39:57.000Z,https://www.trustpilot.com/review/embracepetin...,NaN,NaN,NaN,NaN

In [125]:
embrace_reviews_all['published'] = pd.to_datetime(embrace_reviews_all['published'])

In [126]:
result = embrace_reviews_all.agg(
    Min_Published=('published', 'min'),
    Max_Published=('published', 'max')
).reset_index()

print(result)

           index                 published
0  Min_Published 2019-07-15 15:21:21+00:00
1  Max_Published 2024-04-03 23:37:30+00:00

In [60]:
df_raw = pd.read_csv('/Users/davidreynolds/projects/trustpilot_pet_insurance_reviews/web_scraping/raw/spot_reviews.csv', sep=',')

In [61]:
df_raw.shape

(4347, 10)

In [112]:
df_inc = pd.read_csv('/Users/davidreynolds/projects/trustpilot_pet_insurance_reviews/web_scraping/incremental/trupanion_reviews_incremental.csv', sep=',')

In [113]:
df_inc.shape

(1717, 11)

In [85]:
df_curated = pd.read_csv('/Users/davidreynolds/projects/trustpilot_pet_insurance_reviews/web_scraping/curated/spot_reviews_all.csv', sep=',')

In [86]:
df_curated.shape

(5307, 14)

In [129]:
reviews_for_modeling = pd.read_csv('/Users/davidreynolds/projects/trustpilot_pet_insurance_reviews/data/modeling/reviews_for_modeling.csv', sep=',')

In [130]:
reviews_for_modeling['provider'].value_counts(dropna=False)

provider
aspca          5811
spot           5307
petsbest       4787
embrace        3977
fetch          3520
lemonade       3274
healthypaws    2901
pumpkin        1994
figo           1898
dutch          1835
trupanion      1717
metlife         980
nationwide      940
akc             845
prudent         430
Name: count, dtype: int64

In [114]:
reviews_for_modeling.head()

,provider,review_id,rating,title,text,likes,filtered,pending,experienced_date,published_date,source_url,experienced,source
0,prudent,6a7b257f6a60a00309fdaa63,5,Easy quoting,I could change the coverage and get a cost ver...,0,False,False,2026-08-11T00:00:00.000Z,2026-08-11 15:37:03+00:00,https://www.trustpilot.com/review/prudentpet.com,NaN,NaN
1,prudent,6a7a6c9cadd389d11f537c56,1,I have had Prudent since 2/26 and tried…,I have had Prudent since 2/26 and tried to use...,0,False,False,2026-08-10T00:00:00.000Z,2026-08-11 02:28:13+00:00,https://www.trustpilot.com/review/prudentpet.com,NaN,NaN
2,prudent,6a7a42e03c03455ea08f4ae6,5,Brandy’s was an amazing consultant and…,Brandy’s was an amazing consultant and extreme...,0,False,False,2026-08-08T00:00:00.000Z,2026-08-10 23:30:08+00:00,https://www.trustpilot.com/review/prudentpet.com,NaN,NaN
3,prudent,6a7a1b20f2c98f43678e3eef,1,My first visit to the vet was deny,My first visit to the vet was deny \nthe speci...,0,False,False,2026-07-24T00:00:00.000Z,2026-08-10 20:40:32+00:00,https://www.trustpilot.com/review/prudentpet.com,NaN,NaN
4,prudent,6a795f4d6e05422afe46ac3f,4,They have reasonable rates and reached…,They have reasonable rates and reached out to ...,0,False,False,2026-07-16T00:00:00.000Z,2026-08-10 07:19:09+00:00,https://www.trustpilot.com/review/prudentpet.com,NaN,NaN

In [127]:
reviews_for_modeling['published_date'] = pd.to_datetime(reviews_for_modeling['published_date'])

In [128]:
result = reviews_for_modeling.groupby('provider').agg(
    Min_Published=('published_date', 'min'),
    Max_Published=('published_date', 'max')
).reset_index()

print(result)

       provider             Min_Published             Max_Published
0           akc 2026-01-07 20:46:32+00:00 2026-08-01 02:12:10+00:00
1         aspca 2026-01-06 07:13:21+00:00 2026-08-10 15:52:49+00:00
2         dutch 2026-01-06 02:52:21+00:00 2026-08-10 18:47:47+00:00
3       embrace 2026-01-06 17:53:47+00:00 2026-08-10 16:16:47+00:00
4         fetch 2026-01-06 13:53:51+00:00 2026-08-10 15:07:03+00:00
5          figo 2026-01-10 20:40:12+00:00 2026-08-03 00:40:03+00:00
6   healthypaws 2026-01-07 00:32:55+00:00 2026-08-10 16:26:20+00:00
7      lemonade 2026-01-06 15:08:58+00:00 2026-08-12 11:20:30+00:00
8       metlife 2026-07-05 20:59:22+00:00 2026-08-12 02:50:35+00:00
9    nationwide 2026-04-22 22:48:37+00:00 2026-08-12 02:18:10+00:00
10     petsbest 2026-01-06 17:27:14+00:00 2026-08-11 17:29:52+00:00
11      prudent 2026-01-06 03:20:21+00:00 2026-08-11 15:37:03+00:00
12      pumpkin 2026-01-06 03:51:27+00:00 2026-08-11 22:23:30+00:00
13         spot 2026-04-02 20:29:28+00:00 2026-08-11 23:39:45+00:00
14    trupanion 2026-01-06 04:40:31+00:00 2026-08-11 23:35:42+00:00

In [133]:
akc = pd.read_csv(
    "/Users/davidreynolds/projects/trustpilot_pet_insurance_reviews/web_scraping/curated/akc_reviews_all.csv"
)

akc["published"] = pd.to_datetime(
    akc["published"],
    utc=True
)

print(akc["published"].min())
print(akc["published"].max())
print(len(akc))

2018-01-24 17:08:12+00:00
2024-03-08 05:40:39+00:00
845

In [136]:
raw_akc = pd.read_csv(
    "/Users/davidreynolds/projects/trustpilot_pet_insurance_reviews/web_scraping/raw/akc_reviews.csv"
)

raw_akc["published"] = pd.to_datetime(
    raw_akc["published"],
    utc=True
)

print("RAW")
print("Rows:", len(raw_akc))
print("Min:", raw_akc["published"].min())
print("Max:", raw_akc["published"].max())

print("\nCURATED")
print("Rows:", len(akc))
print("Min:", akc["published"].min())
print("Max:", akc["published"].max())

RAW
Rows: 838
Min: 2018-01-24 17:08:12+00:00
Max: 2024-03-08 05:40:39+00:00

CURATED
Rows: 845
Min: 2018-01-24 17:08:12+00:00
Max: 2024-03-08 05:40:39+00:00

In [135]:
reviews_for_modeling["published_date"] = pd.to_datetime(
    reviews_for_modeling["published_date"],
    utc=True
)

print(
    reviews_for_modeling[
        reviews_for_modeling["provider"] == "akc"
    ]["published_date"].agg(["min", "max"])
)

min   2026-01-07 20:46:32+00:00
max   2026-08-01 02:12:10+00:00
Name: published_date, dtype: datetime64[ns, UTC]